version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/Backend"
    schedule:
      interval: "daily"
    groups:
      minor:
        update-types: ['minor', 'patch']

  - package-ecosystem: "npm"
    directory: "/WebClient"
    schedule:
      interval: "daily"
    groups:
      minor:
        update-types: ['minor', 'patch']
